### ISSUE TITLE
repository dockercomposev2_amity-db not found

### ISSUE THREAD

**Issue by Ahmad31** [davidmukiibi/docker-flask#1]
I get an ERROR message while executing the last command
docker-compose -f docker-compose.yml up
==========================================================================
ahmad@ahmad-S451LB ~/Docker/docker-flask $ docker-compose -f docker-compose.yml up
Pulling amity_db_service (dockercomposev2_amity-db:latest)...
ERROR: repository dockercomposev2_amity-db not found: does not exist or no pull access

**Comment by davidmukiibi** [comment]
The issue you are facing here is with the docker image. 
FIX:
build a docker image of your own. or you can use mine. But to use mine you have to pull them from my repository. use this command (docker pull mukiibi/<image-name-here). But for some reason, i deleted that image from my docker hub repository. So i suggest you build the images yourself first before you run the docker-compose command. 
The same names you give to your docker images should be the same names you use in the docke-compose.yml file. After a successful build, you will have all images on your local machine/computer. 
I hope that fixes the issue.. Feel free to reach out incase of any further assistance.

**Comment by FollowJack** [comment]
Where do you have to put them exactly in your the docker compose file. A minimal example or updated version of your tutorial would be helpful.

**Comment by davidmukiibi** [comment]
I will build a new docker image with that name and push it (as a quick
fix), but a permanent fix would definitely update the article with a
placeholder to your specific docker image.
